# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('callout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2016, 4, 26, 10, 19, 2, 14535, tzinfo=utc))),
                ('state', models.CharField(choices=[('F', 'Following'), ('U', 'Unsure'), ('R', 'Requesting assistance')], default='F', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callout.Status'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='date_ending',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='date_starting',
            field=models.DateField(null=True),
        ),
    ]
