# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callout', '0002_auto_20160426_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
