# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callout', '0003_auto_20160426_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
        migrations.AddField(
            model_name='status',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='callout.Subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callout.User'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callout.Workspace'),
        ),
    ]
