# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callout', '0004_auto_20160426_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='uuid',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='feedback',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callout.User'),
        ),
    ]
