# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callout', '0005_auto_20160426_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='uuid',
            field=models.CharField(max_length=60),
        ),
    ]
