# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callout', '0007_auto_20160426_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='beacons',
            field=models.ManyToManyField(blank=True, to='callout.Beacon'),
        ),
    ]
