# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callout', '0009_auto_20160427_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='uuid',
            field=models.CharField(max_length=70),
        ),
    ]
