# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callout', '0010_auto_20160429_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='creator',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='callout.User'),
            preserve_default=False,
        ),
    ]
