# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callout', '0012_auto_20160429_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callout.Workspace'),
        ),
    ]
