# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callout', '0013_auto_20160511_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='callout.Workspace'),
        ),
    ]
