# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callout', '0014_auto_20160513_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
