# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callout', '0015_auto_20160520_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='callout.User'),
        ),
    ]
